name: Stale Issues

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'Issue stale after 30 days.'
          stale-pr-message: 'PR stale after 14 days.'
          days-before-issue-stale: 30
          days-before-pr-stale: 14
